# OpenTelemetry-native plaintext log configuration
version: '3.8'

services:
  fluent-bit-otel-plaintext:
    image: fluent/fluent-bit:3.0
    container_name: fluent-bit-otel-plaintext
    ports:
      - "24225:24224"  # Different port to avoid conflicts
      - "2021:2020"    # Different metrics port
    volumes:
      - ./fluent-bit-plaintext-otel.yaml:/fluent-bit/etc/fluent-bit.yaml
    command: ["/fluent-bit/bin/fluent-bit", "--config=/fluent-bit/etc/fluent-bit.yaml"]
    restart: unless-stopped