service:
  flush: 5
  daemon: off
  log_level: info
  parsers_file: parsers.conf
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      buffer_chunk_size: 1M
      buffer_max_size: 6M
    - name: dummy
      dummy: '{"timestamp": "2024-01-01T12:00:00Z", "level": "info", "service": "json-service", "message": "Sample JSON log entry", "request_id": "12345"}'
      tag: json.sample

  filters:
    - name: parser
      match: "*"
      key_name: log
      parser: json
      reserve_data: on

  outputs:
    - name: stdout
      match: "*"
      format: json_lines
    - name: http
      match: "*"
      host: api.honeycomb.io
      port: 443
      uri: /1/events/fluent-bit-json
      format: json_lines
      tls: on
      json_date_key: date
      json_date_format: iso8601
      header: X-Honeycomb-Team <Your API Key>
      retry_limit: 3
      log_response_payload: on