service:
  flush: 5
  daemon: off
  log_level: info
  parsers_file: parsers.conf
  http_server: on
  http_listen: 0.0.0.0
  http_port: 2020

pipeline:
  inputs:
    - name: forward
      listen: 0.0.0.0
      port: 24224
      buffer_chunk_size: 1M
      buffer_max_size: 6M
    - name: dummy
      dummy: '{"log": "INFO [2024-01-01 12:00:00] plaintext-service: Sample plaintext log message"}'
      tag: plaintext.sample

  filters:
    - name: modify
      match: "*"
      add: service.name plaintext-service
      add: severity info
      add: environment production
      add: version 1.0.0
      add: team backend
      add: region us-east-1
      add: meta.signal.type log
    - name: modify
      match: "*"
      rename: log body

  outputs:
    - name: stdout
      match: "*"
      format: json_lines
    - name: http
      match: "*"
      host: api.honeycomb.io
      port: 443
      uri: /1/events/fluent-bit-plaintext
      format: json_lines
      tls: on
      json_date_key: date
      json_date_format: iso8601
      header: X-Honeycomb-Team <Your API Key>
      retry_limit: 3
      log_response_payload: on